# OpenAI configuration for CRE Deal Finder

# OpenAI API settings
openai:
  # API key - you need to provide this
  # Either set it here, set the OPENAI_API_KEY environment variable, 
  # or enter it when prompted
  api_key: null  # Replace with your OpenAI API key
  
  # Model to use - options include:
  # - o1: Most advanced model (RECOMMENDED FOR FREE CREDITS)
  # - gpt-4o: Strong model with good balance
  # - gpt-4o-mini: Smaller version, faster but less accurate
  # - o1-mini: Smaller version of o1
  # - o3-mini: Alternative smaller model
  model: "o1"
  
  # Advanced settings
  temperature: 0.2  # Lower for more consistent responses
  max_tokens: 2000  # Response length limit

# Scoring configuration
scoring:
  # Weights for the final score calculation
  seller_motivation_weight: 0.4
  transaction_complexity_weight: 0.3
  property_characteristics_weight: 0.3
  
  # Threshold for highlighting high-potential opportunities
  highlight_threshold: 7  # Properties scoring above this will be highlighted
